// Geometry profiles and flight values are game approximations, not aircraft specifications.
const defineEngine=(name,x,y,z)=>({name,position:{x,y,z},side:Math.sign(x)});
export const AIRCRAFT = Object.freeze([
 {id:'twin',name:'Twin-engine trainer',geometry:'twin',clearance:3.2,thrust:13,liftSpeed:72,pitchRate:.48,rollRate:1.1,fuelBurn:.055,engines:[defineEngine('1 · Left',-5,-1.1,0),defineEngine('2 · Right',5,-1.1,0)]},
 {id:'dc10',name:'McDonnell Douglas DC-10',geometry:'dc10',clearance:4.4,thrust:13,liftSpeed:72,pitchRate:.44,rollRate:.9,fuelBurn:.065,engines:[defineEngine('1 · Left wing',-7,-1.6,0),defineEngine('2 · Tail',0,3.6,-15),defineEngine('3 · Right wing',7,-1.6,0)]},
 {id:'b747',name:'Boeing 747',geometry:'b747',clearance:4.4,thrust:13,liftSpeed:72,pitchRate:.42,rollRate:.75,fuelBurn:.075,engines:[defineEngine('1 · Left outer',-14,-1.3,-2.8),defineEngine('2 · Left inner',-7,-1.6,0),defineEngine('3 · Right inner',7,-1.6,0),defineEngine('4 · Right outer',14,-1.3,-2.8)]},
{"id": "c172", "name": "Cessna 172 Skyhawk", "category": "Small planes", "tip": "Start here \u00b7 light and responsive", "clearance": 1.5, "geometry": "fleet", "visual": {"length": 8.28, "span": 11, "radius": 0.65, "wingY": 0.75, "sweep": 0.2, "tailHeight": 1.6, "tailWingY": 0.2, "prop": 2, "engineRadius": 0.38}, "thrust": 5, "liftSpeed": 34, "approachSpeed": 34, "takeoffSpeed": 34, "pitchRate": 0.45, "rollRate": 0.85, "fuelBurn": 0.025, "fixedGear": true, "engines": [{"name": "1", "position": {"x": 0, "y": 0, "z": 3.1}, "side": 0}]},
{"id": "dc3", "name": "Douglas DC-3", "category": "Classic planes", "tip": "Classic twin propeller \u00b7 gentle turns", "clearance": 2.6, "geometry": "fleet", "visual": {"length": 19.66, "span": 28.96, "radius": 1.3, "wingY": -0.6, "sweep": 2.5, "tailHeight": 3.8, "tailWingY": 0.8, "prop": 3, "engineRadius": 0.9, "tailwheel": true}, "thrust": 9, "liftSpeed": 48, "approachSpeed": 48, "takeoffSpeed": 48, "pitchRate": 0.45, "rollRate": 0.85, "fuelBurn": 0.025, "fixedGear": false, "engines": [{"name": "1", "position": {"x": -4, "y": -0.4, "z": 3}, "side": -1}, {"name": "2", "position": {"x": 4, "y": -0.4, "z": 3}, "side": 1}]},
{"id": "a320", "name": "Airbus A320", "category": "Airliners", "tip": "Twin wing engines \u00b7 upright wingtip fins", "clearance": 4.2, "geometry": "fleet", "visual": {"length": 37.57, "span": 35.8, "radius": 1.98, "wingY": -1, "sweep": 6, "tailHeight": 6.5, "tailWingY": 0.5, "winglets": 2, "engineRadius": 1.05}, "thrust": 18, "liftSpeed": 70, "approachSpeed": 70, "takeoffSpeed": 70, "pitchRate": 0.45, "rollRate": 0.85, "fuelBurn": 0.04, "fixedGear": false, "engines": [{"name": "1", "position": {"x": -5.8, "y": -2, "z": 3}, "side": -1}, {"name": "2", "position": {"x": 5.8, "y": -2, "z": 3}, "side": 1}]},
{"id": "b737", "name": "Boeing 737-800", "category": "Airliners", "tip": "Long narrow body \u00b7 swept winglets", "clearance": 4, "geometry": "fleet", "visual": {"length": 39.47, "span": 35.8, "radius": 1.88, "wingY": -1.1, "sweep": 7.1, "tailHeight": 6, "tailWingY": 0.5, "winglets": 2.5, "engineRadius": 0.9}, "thrust": 18, "liftSpeed": 70, "approachSpeed": 70, "takeoffSpeed": 70, "pitchRate": 0.45, "rollRate": 0.85, "fuelBurn": 0.04, "fixedGear": false, "engines": [{"name": "1", "position": {"x": -5.6, "y": -1.8, "z": 3.5}, "side": -1}, {"name": "2", "position": {"x": 5.6, "y": -1.8, "z": 3.5}, "side": 1}]},
{"id": "dc9", "name": "Douglas DC-9-30", "category": "Classic planes", "tip": "Two rear engines \u00b7 tall T-shaped tail", "clearance": 3.7, "geometry": "fleet", "visual": {"length": 36.37, "span": 28.44, "radius": 1.67, "wingY": -0.9, "sweep": 5, "tailHeight": 6.5, "tailWingY": 6, "engineRadius": 0.72}, "thrust": 16, "liftSpeed": 65, "approachSpeed": 65, "takeoffSpeed": 65, "pitchRate": 0.45, "rollRate": 0.85, "fuelBurn": 0.04, "fixedGear": false, "engines": [{"name": "1", "position": {"x": -2.8, "y": 1, "z": -11}, "side": -1}, {"name": "2", "position": {"x": 2.8, "y": 1, "z": -11}, "side": 1}]},
{"id": "g650", "name": "Gulfstream G650ER", "category": "Private jets", "tip": "Private jet \u00b7 oval windows and T-tail", "clearance": 3.1, "geometry": "fleet", "visual": {"length": 30.41, "span": 30.35, "radius": 1.28, "wingY": -0.6, "sweep": 6, "tailHeight": 5.5, "tailWingY": 5, "winglets": 1.8, "engineRadius": 0.72}, "thrust": 11, "liftSpeed": 62, "approachSpeed": 62, "takeoffSpeed": 62, "pitchRate": 0.45, "rollRate": 0.85, "fuelBurn": 0.04, "fixedGear": false, "engines": [{"name": "1", "position": {"x": -2.2, "y": 0.8, "z": -9}, "side": -1}, {"name": "2", "position": {"x": 2.2, "y": 0.8, "z": -9}, "side": 1}]},
{"id": "c130", "name": "Lockheed C-130J Hercules", "category": "Cargo planes", "tip": "Cargo hauler \u00b7 four six-blade propellers", "clearance": 4.2, "geometry": "fleet", "visual": {"length": 29.79, "span": 40.41, "radius": 2, "wingY": 1.5, "sweep": 1.7, "tailHeight": 8, "tailWingY": 2.8, "prop": 6, "engineRadius": 0.8, "cargo": true}, "thrust": 9, "liftSpeed": 55, "approachSpeed": 55, "takeoffSpeed": 55, "pitchRate": 0.45, "rollRate": 0.85, "fuelBurn": 0.025, "fixedGear": false, "engines": [{"name": "1", "position": {"x": -12, "y": 1, "z": 3}, "side": -1}, {"name": "2", "position": {"x": -6, "y": 1, "z": 3}, "side": -1}, {"name": "3", "position": {"x": 6, "y": 1, "z": 3}, "side": 1}, {"name": "4", "position": {"x": 12, "y": 1, "z": 3}, "side": 1}]}
]);
export function getAircraft(id){const aircraft=AIRCRAFT.find(a=>a.id===id);if(!aircraft)throw new Error('Unknown aircraft: '+id);return aircraft}
