import {AIRCRAFT} from './aircraft-catalog.js';
import {MODES,LIVERIES,CABINS,GATES} from './flight-config.js';
const $=id=>document.getElementById(id);
const planeIcon=(family)=>`<svg viewBox="0 0 260 100" aria-hidden="true"><path fill="currentColor" d="M18 54 L91 47 L124 9 L139 9 L127 47 L223 49 Q247 52 227 59 L126 59 L138 90 L125 90 L94 61 L34 62 L18 84 L9 84 L14 57 L5 35 L14 35Z"/>${family==='b747'?'<path fill="currentColor" d="M165 46L172 39H205L217 49Z"/>':''}</svg>`;
export function createSetup({start,preview,opening}){
 let step=0,draft={mode:'departure',aircraft:'b747',livery:'horizon',start:'gate',gate:'g1',runway:'01',passengers:320,fuel:80};
 const sections=['Choose your flight','Choose your aircraft','Choose your livery','Choose your starting point','Prepare your departure'];
 function cards(items,key,content){return `<div class="selection-grid ${key==='mode'?'mode-grid':''}">${items.map(item=>`<button class="select-card ${draft[key]===item.id?'selected':''}" data-choice="${key}" data-value="${item.id}" aria-pressed="${draft[key]===item.id}">${content(item)}</button>`).join('')}</div>`}
 function draw(){
 $('setup-heading').textContent=sections[step];$('setup-progress').textContent=`${step+1} / 5 · ${['FLIGHT','AIRCRAFT','LIVERY','LOCATION','MANIFEST'][step]}`;
 $('setup-back').disabled=step===0;$('setup-next').disabled=false;$('setup-next').textContent=step===4?'START FLIGHT →':'CONTINUE →';
 let html='';
 if(step===0)html=cards(MODES,'mode',m=>`<span class="card-number">${m.mark}</span><strong>${m.name}</strong><span>${m.caption}</span>`);
 if(step===1)html=cards(AIRCRAFT,'aircraft',a=>`${planeIcon(a.id)}<strong>${a.name}</strong><span>${CABINS[a.id].capacity} passenger layout · ${a.engines.length} engines</span>`);
 if(step===2)html=cards(LIVERIES,'livery',l=>`<div class="livery-preview" style="color:${l.color};background:linear-gradient(145deg,${l.accent}44,#e7eef5)">${planeIcon(draft.aircraft)}<b>${l.label||'UNPAINTED'}</b></div><strong>${l.name}</strong><span>Original game livery</span>`);
 if(step===3){const dep=draft.mode==='departure';html=`<div class="airport-summary"><b>HORIZON INTERNATIONAL</b><span>One airport · 18 gates · Runway 01 / 19</span></div><div class="location-options"><label>Departure runway<select id="setup-runway"><option value="01" ${draft.runway==='01'?'selected':''}>01 · northbound</option><option value="19" ${draft.runway==='19'?'selected':''}>19 · southbound</option></select></label>${dep?`<label>Start from<select id="setup-start"><option value="gate" ${draft.start==='gate'?'selected':''}>Passenger gate</option><option value="runway" ${draft.start==='runway'?'selected':''}>Runway · ready for takeoff</option></select></label>`:'<p>Start airborne. Landing practice aligns with the selected runway.</p>'}</div><div class="airport-map" aria-label="Airport gate map"><div class="map-runway">01 ━━━ RUNWAY ━━━ 19</div><div class="map-taxiway"></div><div class="gate-grid">${GATES.map(g=>`<button data-choice="gate" data-value="${g.id}" class="gate ${draft.gate===g.id?'selected':''}" ${!dep||draft.start!=='gate'?'disabled':''} aria-pressed="${draft.gate===g.id}" aria-label="${g.name}">${g.name.replace('Gate ','G')}</button>`).join('')}</div><div class="map-terminal">PASSENGER TERMINAL</div></div><p class="muted">${dep&&draft.start==='gate'?GATES.find(g=>g.id===draft.gate).name+' selected · pushback available on arrival.':'Runway '+draft.runway+' selected.'}</p>`}
 if(step===4){const c=CABINS[draft.aircraft];html=`<div class="manifest-grid"><section><label for="setup-passengers">Passengers <b id="passenger-count">${draft.passengers} / ${c.capacity}</b></label><input id="setup-passengers" type="range" min="0" max="${c.capacity}" value="${draft.passengers}"><label for="setup-fuel">Fuel <b id="fuel-count">${draft.fuel}%</b></label><input id="setup-fuel" type="range" min="0" max="100" value="${draft.fuel}"><p>${c.crew} crew aboard · Higher loads need more runway.</p><div class="cabin-diagram" aria-label="Cabin occupancy preview">${Array.from({length:30},(_,i)=>`<i class="${i<Math.round(draft.passengers/c.capacity*30)?'occupied':''}"></i>`).join('')}</div><p class="muted">Passengers are simulated by cabin section. No animated cabin interior.</p></section><section class="flight-summary"><span>YOUR FLIGHT</span><h3>${AIRCRAFT.find(a=>a.id===draft.aircraft).name}</h3><p>${LIVERIES.find(l=>l.id===draft.livery).name}</p><p>${MODES.find(m=>m.id===draft.mode).name}</p><p>Horizon International<br>Runway ${draft.runway}${draft.mode==='departure'&&draft.start==='gate'?' · '+GATES.find(g=>g.id===draft.gate).name:''}</p><small>Crash reports use fictional game rules for cabin damage, fire and evacuation.</small></section></div>`}
 $('setup-content').innerHTML=html;
 $('setup-content').querySelectorAll('[data-choice]').forEach(b=>b.onclick=()=>{const key=b.dataset.choice;draft[key]=b.dataset.value;if(key==='aircraft')draft.passengers=Math.min(draft.passengers,CABINS[draft.aircraft].capacity);preview(draft);draw()});
 for(const key of ['runway','start']){const el=$('setup-'+key);if(el)el.onchange=()=>{draft[key]=el.value;draw()}}
 if(step===4){$('setup-passengers').oninput=e=>{draft.passengers=Number(e.target.value);$('passenger-count').textContent=`${draft.passengers} / ${cabinCapacity()}`;$('setup-content').querySelectorAll('.cabin-diagram i').forEach((el,i)=>el.classList.toggle('occupied',i<Math.round(draft.passengers/cabinCapacity()*30)))};$('setup-fuel').oninput=e=>{draft.fuel=Number(e.target.value);$('fuel-count').textContent=draft.fuel+'%'}}
 }
 function cabinCapacity(){return CABINS[draft.aircraft].capacity}
 $('setup-back').onclick=()=>{step=Math.max(0,step-1);draw()};$('setup-next').onclick=()=>{if(step<4){step++;draw()}else{$('setup').classList.add('hidden');document.body.classList.remove('setup-open');start({...draft})}};
 return {open(){opening();step=0;$('setup').classList.remove('hidden');document.body.classList.add('setup-open');draw();preview(draft)}};
}
