import {AIRCRAFT} from './aircraft-catalog.js';
import {MODES,LIVERIES,CABINS,GATES} from './flight-config.js';
const $=id=>document.getElementById(id);
const planeIcon=(id)=>{const a=AIRCRAFT.find(a=>a.id===id),v=a?.visual; if(!v)return `<svg viewBox="0 0 260 100" aria-hidden="true"><path fill="currentColor" d="M18 54L91 47L124 9H139L127 47L223 49Q247 52 227 59L126 59L138 90H125L94 61H34L18 84H9L14 57L5 35H14Z"/></svg>`;const scale=80/Math.max(v.span,v.length),L=v.length*scale,S=v.span*scale/2,sw=v.sweep*scale;return `<svg viewBox="0 0 180 100" aria-hidden="true"><g transform="translate(90 50)"><ellipse rx="${v.radius*scale}" ry="${L/2}" fill="currentColor"/><path d="M-2 -8L${-S} ${sw-6}V${sw+3}L-2 8H2L${S} ${sw+3}V${sw-6}L2 -8Z M-1 ${L*.3}L${-S*.32} ${L*.43}V${L*.47}H${S*.32}V${L*.43}L1 ${L*.3}Z" fill="currentColor"/>${a.engines.map(e=>`<rect x="${e.position.x*scale-2}" y="${-e.position.z*scale-3}" width="4" height="8" rx="2" fill="currentColor"/>${v.prop?`<path d="M${e.position.x*scale-5} ${-e.position.z*scale-4}h10" stroke="currentColor" stroke-width="2"/>`:''}`).join('')}</g></svg>`};
export function createSetup({start,preview,opening}){
 let step=0,draft={mode:'departure',aircraft:'c172',livery:'delta',start:'runway',gate:'g1',runway:'01',passengers:3,fuel:80};
 const sections=['Choose your flight','Pick your plane','Pick your airline colors','Where do you want to start?','Ready to fly?'];
 function cards(items,key,content){return `<div class="selection-grid ${key==='mode'?'mode-grid':''}">${items.map(item=>`<button class="select-card ${draft[key]===item.id?'selected':''}" data-choice="${key}" data-value="${item.id}" aria-pressed="${draft[key]===item.id}">${content(item)}</button>`).join('')}</div>`}
 function draw(){
 $('setup-heading').textContent=sections[step];$('setup-progress').textContent=`${step+1} / 5 · ${['FLIGHT','PLANE','COLORS','START','READY'][step]}`;
 $('setup-back').disabled=step===0;$('setup-next').disabled=false;$('setup-next').textContent=step===4?'START FLIGHT →':'CONTINUE →';
 let html='';
 if(step===0)html=cards(MODES,'mode',m=>`<span class="card-number">${m.mark}</span><strong>${m.name}</strong><span>${m.caption}</span>`);
 if(step===1)html='<p class="fleet-hint">New pilot? Try the Cessna 172. Every plane is unlocked.</p>'+cards([...AIRCRAFT.filter(a=>a.visual),...AIRCRAFT.filter(a=>!a.visual)],'aircraft',a=>`<span class="plane-category">${a.category||(a.id==='twin'?'Small planes':'Large planes')}</span>${planeIcon(a.id)}<strong>${a.name}</strong><span>${a.tip||(a.id==='twin'?'Twin engines · practice your flying':'Large aircraft · plan your turns early')}</span><span>${CABINS[a.id].capacity===0?'Cargo flight':CABINS[a.id].capacity+' passenger seats'} · ${a.engines.length} engine${a.engines.length===1?'':'s'}</span>`);
 if(step===2)html=cards(LIVERIES,'livery',l=>`<div class="livery-preview" style="color:${l.color};background:linear-gradient(145deg,${l.accent}44,#e7eef5)"><img class="airline-logo" src="${l.logo}" alt="${l.name} logo"></div><strong>${l.name}</strong><span>Airline colors & decals</span>`);
 if(step===3){const dep=draft.mode==='departure';html=`<div class="airport-summary"><b>HORIZON INTERNATIONAL</b><span>One airport · 18 gates · Runway 01 / 19</span></div><div class="location-options"><label>Departure runway<select id="setup-runway"><option value="01" ${draft.runway==='01'?'selected':''}>01 · northbound</option><option value="19" ${draft.runway==='19'?'selected':''}>19 · southbound</option></select></label>${dep?`<label>Start from<select id="setup-start"><option value="gate" ${draft.start==='gate'?'selected':''}>Passenger gate</option><option value="runway" ${draft.start==='runway'?'selected':''}>Runway · ready for takeoff</option></select></label>`:'<p>Start airborne. Landing practice aligns with the selected runway.</p>'}</div><div class="airport-map" aria-label="Airport gate map"><div class="map-runway">01 ━━━ RUNWAY ━━━ 19</div><div class="map-taxiway"></div><div class="gate-grid">${GATES.map(g=>`<button data-choice="gate" data-value="${g.id}" class="gate ${draft.gate===g.id?'selected':''}" ${!dep||draft.start!=='gate'?'disabled':''} aria-pressed="${draft.gate===g.id}" aria-label="${g.name}">${g.name.replace('Gate ','G')}</button>`).join('')}</div><div class="map-terminal">PASSENGER TERMINAL</div></div><p class="muted">${dep&&draft.start==='gate'?GATES.find(g=>g.id===draft.gate).name+' selected · pushback available on arrival.':'Runway '+draft.runway+' selected.'}</p>`}
 if(step===4){const c=CABINS[draft.aircraft];html=`<div class="manifest-grid"><section><label for="setup-passengers">Passengers <b id="passenger-count">${draft.passengers} / ${c.capacity}</b></label><input id="setup-passengers" type="range" min="0" max="${c.capacity}" value="${draft.passengers}"><label for="setup-fuel">Fuel <b id="fuel-count">${draft.fuel}%</b></label><input id="setup-fuel" type="range" min="0" max="100" value="${draft.fuel}"><p>${c.crew} crew aboard · More passengers and fuel make your plane heavier.</p><div class="cabin-diagram" aria-label="Cabin occupancy preview">${Array.from({length:30},(_,i)=>`<i class="${i<Math.round(draft.passengers/c.capacity*30)?'occupied':''}"></i>`).join('')}</div><p class="muted">Choose how many passengers come along.</p></section><section class="flight-summary"><span>YOUR FLIGHT</span><h3>${AIRCRAFT.find(a=>a.id===draft.aircraft).name}</h3><p>${LIVERIES.find(l=>l.id===draft.livery).name}</p><p>${MODES.find(m=>m.id===draft.mode).name}</p><p>Horizon International<br>Runway ${draft.runway}${draft.mode==='departure'&&draft.start==='gate'?' · '+GATES.find(g=>g.id===draft.gate).name:''}</p><small>Practice flying, explore, or try an emergency. Crash results are fictional game outcomes.</small></section></div>`}
 $('quick-start').classList.toggle('hidden',step!==1);$('setup-content').innerHTML=html;
 $('setup-content').querySelectorAll('[data-choice]').forEach(b=>b.onclick=()=>{const key=b.dataset.choice;draft[key]=b.dataset.value;if(key==='aircraft')draft.passengers=Math.min(draft.passengers,CABINS[draft.aircraft].capacity);preview(draft);draw()});
 for(const key of ['runway','start']){const el=$('setup-'+key);if(el)el.onchange=()=>{draft[key]=el.value;draw()}}
 if(step===4){$('setup-passengers').disabled=cabinCapacity()===0;$('setup-passengers').oninput=e=>{draft.passengers=Number(e.target.value);$('passenger-count').textContent=`${draft.passengers} / ${cabinCapacity()}`;$('setup-content').querySelectorAll('.cabin-diagram i').forEach((el,i)=>el.classList.toggle('occupied',i<Math.round(draft.passengers/cabinCapacity()*30)))};$('setup-fuel').oninput=e=>{draft.fuel=Number(e.target.value);$('fuel-count').textContent=draft.fuel+'%'}}
 }
 function cabinCapacity(){return CABINS[draft.aircraft].capacity}
 $('quick-start').onclick=()=>{$('setup').classList.add('hidden');document.body.classList.remove('setup-open');start({...draft,mode:'departure',start:'runway',fuel:80})};
 $('setup-back').onclick=()=>{step=Math.max(0,step-1);draw()};$('setup-next').onclick=()=>{if(step<4){step++;draw()}else{$('setup').classList.add('hidden');document.body.classList.remove('setup-open');start({...draft})}};
 return {open(){opening();step=0;$('setup').classList.remove('hidden');document.body.classList.add('setup-open');draw();preview(draft)}};
}
